global:
  environment: "dev"
  replicaCount: 1

frontend:
  image:
    repository: nottiey/frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer   # ✅ To expose externally
    port: 80
    targetPort: 80       # ✅ Match Nginx container port

  ingress:
    enabled: false
    host: "react.example.com"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: nginx

backend:
  image:
    repository: nottiey/backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
