# helm/umbrella-chart/values.yaml

# Global settings for the applications
global:
  environment: "dev" # e.g., dev, prod, staging
  replicaCount: 1

frontend:
  # Values specific to the frontend subchart
  image:
    repository: nottiey/frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer  # ✅ Changed from ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: false
    host: "react.example.com"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: nginx
      # cert-manager.io/cluster-issuer: "letsencrypt-prod"

backend:
  # Values specific to the backend subchart
  image:
    repository: nottiey/backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
