replicaCount: 1

image:
  repository: nottiey/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer    # Updated from ClusterIP to expose frontend via ELB
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /
  pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
