replicaCount: 1

image:
  repository: nottiey/backend
  tag: "17-jdk-slim" # Will be replaced with your Java app image later
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080 # Default Spring Boot port
  targetPort: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi # Increased memory limit to prevent OOM
  requests:
    cpu: 250m
    memory: 256Mi # Increased memory request

# Temporarily disable probes for this placeholder container
probes:
  liveness:
    enabled: false # Disable liveness probe
  readiness:
    enabled: false # Disable readiness probe

# Environment variables for the backend application
env: []

nodeSelector: {}

tolerations: []

affinity: {}
